[package]
name = "netconf"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
netlink-sys = "0.8.2"
netlink-packet-route = "0.11.0"

[profile.release]
opt-level = "z"
lto = true
panic = "abort"
